version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  # api:
  #   build: ./cmd/api
  #     command: go run cmd/api/api.go
  #     volumes:
  #         - ./server:/go/src/app
  #     ports:
  #         - "8080:8080"
volumes:
  data:
